import js from "@eslint/js";
import tseslint from "typescript-eslint";
import nextPlugin from "@next/eslint-plugin-next";
import reactPlugin from "eslint-plugin-react";
import hooksPlugin from "eslint-plugin-react-hooks";

export default tseslint.config(
  // ── Ignore build artefacts across all workspaces ──────────────────────────
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/build/**",
      "**/*.config.ts",
      "**/*.config.js",
      "**/*.config.mjs",
      // Auto-generated by Next.js — not user code
      "**/next-env.d.ts",
    ],
  },

  // ── Base JS recommended rules ─────────────────────────────────────────────
  js.configs.recommended,

  // ── TypeScript recommended rules (all .ts / .tsx files) ───────────────────
  ...tseslint.configs.recommended,

  // ── Common rules for all TypeScript files ─────────────────────────────────
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      // Disable base rule — TS-aware version handles this correctly
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          vars: "all",
          args: "after-used",
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: false,
        },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },

  // ── Common rules for plain JS files ───────────────────────────────────────
  {
    files: ["**/*.{js,mjs,cjs}"],
    rules: {
      "no-unused-vars": [
        "error",
        {
          vars: "all",
          args: "after-used",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: false,
        },
      ],
    },
  },

  // ── React + Next.js rules (apps only) ─────────────────────────────────────
  {
    files: ["apps/**/*.{ts,tsx}"],
    plugins: {
      "@next/next": nextPlugin,
      react: reactPlugin,
      "react-hooks": hooksPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      ...reactPlugin.configs.recommended.rules,
      ...hooksPlugin.configs.recommended.rules,
      // React 17+ JSX transform — no need to import React in scope
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      // App Router: no pages/ directory, rule requires explicit config
      "@next/next/no-html-link-for-pages": "off",
    },
    settings: {
      react: { version: "detect" },
    },
  },

  // ── Shared package (no Next.js / browser globals needed) ──────────────────
  {
    files: ["shared/src/**/*.{ts,tsx}"],
  },
);
